this.state = {
    hedgehogs: [
        {
            name: "Felicity",
            birthday: "",
            age: 2,
            friendliness: "Calm",
            breed: "African-pygmy",
            gender: "Female",
            color: "",
            Image: "",
            Info: "",
        },
        {
            name: "Bruce",
            birthday: "",
            age: 2,
            friendliness: "Needs work",
            breed: "",
            gender: "",
            color: "",
            Image: "",
            Info: "",
        },
        {
            name: "Corrin",
            birthday: "",
            age: 2,
            friendliness: "Calm",
            breed: "",
            gender: "",
            color: "",
            Image: "",
            Info: "",
        },
        {
            name: "Hailey",
            birthday: "",
            age: 2,
            friendliness: "Calm",
            breed: "",
            gender: "",
            color: "",
            Image: "",
            Info: "",
        },
        {
            name: "Spike",
            birthday: "",
            age: 2,
            friendliness: "Grumpy",
            breed: "",
            gender: "",
            color: "",
            Image: "",
            Info: "",
        },
        {
            name: "Sonic",
            birthday: "",
            age: 2,
            friendliness: "Grumpy",
            breed: "",
            gender: "",
            color: "",
            Image: "",
            Info: "Gotta go Fast!",
        },
        {
            name: "Samus",
            birthday: "",
            age: 2,
            friendliness: "calm",
            breed: "African-Pygmy",
            gender: "Female",
            color: "Platinum",
            Image: "",
            Info: "",
        },
        {
            name: "Vona",
            birthday: "",
            age: 2,
            friendliness: "Needs work",
            breed: "Algerian",
            gender: "Female",
            color: "Algerian Black",
            Image: "",
            Info: "",
        },
        {
            name: "Cloud",
            birthday: "",
            age: 2,
            friendliness: "Calm",
            breed: "African-Pygmy",
            gender: "Male",
            color: "Albino",
            Image: "",
            Info: "",
        },
        {
            name: "Cinnamon",
            birthday: "",
            age: 2,
            friendliness: "Grumpy",
            breed: "Algerian",
            gender: "Male",
            color: "Algerian Cinnamon",
            Image: "",
            Info: "",
        },
    ]
}